import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import FloatingCreatePostButton from "@/components/floatingButton";

import BottomNav from "@/components/navbar";

export const metadata: Metadata = {
  title: "bluberd",
  description: "Generated by Soban",
  icons: {
    icon: "/bluberd.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
        <AuthProvider>
          <header className="sticky top-0 z-50 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 shadow-sm">
            <div className="max-w-4xl mx-auto flex items-center justify-center px-4 py-3">
              <div className="flex items-center gap-2">
                <img
                  src="/bluberd.png"
                  alt="bluberd logo"
                  className="w-6 h-6"
                />
                <span className="text-xl font-semibold text-black dark:text-white">
                  BluBerd
                </span>
              </div>
            </div>
          </header>

          {children}
          <FloatingCreatePostButton />
          <BottomNav />
        </AuthProvider>
      </body>
    </html>
  );
}
